# Part 2 — Production overlay

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-alpha-prod

resources:
- ../../base

images:
- name: team-alpha-backend-blue
  newName: dawnhealthacr.azurecr.io/team-alpha/backend
  newTag: v1.0.0
- name: team-alpha-backend-green
  newName: ecapacr.azurecr.io/team-alpha/backend
  newTag: 19-76d3bc21111e5d8c03cfee817e5d0e45dc8ddd1e
